# -*- coding: utf-8 -*-
"""sentiment analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tEsedSAfuDlkS3xcl4zSsai3biILtHS
"""

!pip install transformers torch gradio

import gradio as gr
from transformers import pipeline

# Load pre-trained sentiment analysis model
sentiment_model = pipeline("sentiment-analysis")

# Prediction function
def analyze_sentiment(text):
    if not text.strip():
        return "Please enter some text!", None

    result = sentiment_model(text)[0]
    label = result['label']
    score = result['score']

    sentiment = "😊 Positive" if label == "POSITIVE" else "😞 Negative"
    confidence = f"{score:.2f}"

    return sentiment, confidence

# Gradio Interface
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        <h1 style='text-align:center; color:#4CAF50;'>📊 Sentiment Analysis App</h1>
        <p style='text-align:center;'>Analyze the sentiment of any text using a pre-trained NLP model.</p>
        """
    )

    with gr.Row():
        with gr.Column():
            text_input = gr.Textbox(
                placeholder="Type your sentence here...",
                label="Enter Text",
                lines=4
            )
            submit_btn = gr.Button("Analyze Sentiment")

        with gr.Column():
            sentiment_output = gr.Textbox(label="Predicted Sentiment")
            confidence_output = gr.Textbox(label="Confidence Score")

    submit_btn.click(
        analyze_sentiment,
        inputs=text_input,
        outputs=[sentiment_output, confidence_output]
    )

# Run on Colab
demo.launch(share=True)

demo.launch(share=True)

